using Sts2PilotTrainer.FormatReference;
using Sts2PilotTrainer.IO;

namespace Sts2PilotTrainer.Replay.Tests;

/// <summary>
/// Whether docs/manifest-format.md describes the validator that exists.
///
/// The reference is generated by reading two declarations, and reading a declaration
/// is not the same as running it: a reader that misunderstood an arm would produce a
/// document that is confident, well formed and wrong, which is worse than no document
/// at all. So every claim it makes about a verb is put back to the real validator
/// here - drop a required argument and it must complain about that argument, add a
/// name the reference does not list and it must call it unknown - and the parse is
/// only trusted where the validator agrees with it.
///
/// Whether the committed file is the one the generator produces is a different
/// question, and CI answers it: ./scripts/format-reference.sh --check.
/// </summary>
public class ManifestFormatReferenceTests
{
    private static readonly string Root = WorktreeLocator.Find();

    private static readonly IReadOnlyList<VerbArguments> Rules = ValidatorSource.Read(Root);

    private static readonly IReadOnlyList<string> NonEmpty = ValidatorSource.ReadNonEmptyArguments(Root);

    private static readonly IReadOnlyList<(string Argument, IReadOnlyList<string> Values)> Enumerated =
        ValidatorSource.ReadEnumeratedArguments(Root);

    public static TheoryData<string> Verbs()
    {
        var data = new TheoryData<string>();
        foreach (var rule in Rules)
        {
            data.Add(rule.Verb);
        }

        return data;
    }

    [Fact]
    public void TheReferenceAccountsForEveryVerbTheFormatNames()
    {
        var (mapped, unmapped) = EngineCommandSource.Read(Root);
        var described = Rules.Select(rule => rule.Verb)
            .Concat(unmapped.Keys)
            .ToHashSet(StringComparer.Ordinal);

        Assert.Equal(
            Enum.GetValues<ActionVerb>().Select(verb => verb.ToString()).OrderBy(verb => verb, StringComparer.Ordinal),
            described.OrderBy(verb => verb, StringComparer.Ordinal));
        Assert.Equal(Rules.Count, mapped.Count);
    }

    /// <summary>An action carrying exactly what the reference calls required is accepted.</summary>
    [Theory]
    [MemberData(nameof(Verbs))]
    public void WhatTheReferenceCallsRequiredIsEnough(string verb)
    {
        var rule = Rule(verb);
        Assert.Empty(ArgumentProblems(rule, Baseline(rule)));
    }

    [Theory]
    [MemberData(nameof(Verbs))]
    public void EveryRequiredArgumentIsRefusedWhenItIsMissing(string verb)
    {
        var rule = Rule(verb);
        foreach (var name in rule.Required)
        {
            var args = Baseline(rule);
            args.Remove(name);
            Assert.Contains(
                ArgumentProblems(rule, args),
                problem => problem.Contains($"missing required argument '{name}'", StringComparison.Ordinal));
        }
    }

    [Theory]
    [MemberData(nameof(Verbs))]
    public void AnArgumentTheReferenceDoesNotListIsRefused(string verb)
    {
        var rule = Rule(verb);
        var args = Baseline(rule);
        args["not_an_argument_any_verb_has"] = "1";
        Assert.Contains(
            ArgumentProblems(rule, args),
            problem => problem.Contains("unknown argument 'not_an_argument_any_verb_has'", StringComparison.Ordinal));
    }

    /// <summary>
    /// Every optional argument at once, rather than one at a time.
    ///
    /// The optional ones are almost all negative-control nominations, and the validator
    /// refuses a nomination whose other half is absent or whose value is the decision
    /// that was actually made. Offering them singly would test that rule instead of this
    /// one and fail for the wrong reason.
    /// </summary>
    [Theory]
    [MemberData(nameof(Verbs))]
    public void EveryArgumentTheReferenceAllowsIsAccepted(string verb)
    {
        var rule = Rule(verb);
        var args = Baseline(rule);
        foreach (var name in rule.Allowed.Where(name => !args.ContainsKey(name)))
        {
            args[name] = Distinct(name, rule);
        }

        Assert.DoesNotContain(
            ArgumentProblems(rule, args),
            problem => problem.Contains("unknown argument", StringComparison.Ordinal));
    }

    [Theory]
    [MemberData(nameof(Verbs))]
    public void EveryArgumentTheReferenceCallsAnIntegerIsCheckedAsOne(string verb)
    {
        var rule = Rule(verb);
        foreach (var name in rule.NonNegativeIntegers.Where(rule.Required.Contains))
        {
            var args = Baseline(rule);
            args[name] = "-1";
            Assert.Contains(
                ArgumentProblems(rule, args),
                problem => problem.Contains(
                    $"argument '{name}' must be a canonical non-negative integer", StringComparison.Ordinal));
        }
    }

    [Theory]
    [MemberData(nameof(Verbs))]
    public void EveryArgumentTheReferenceCallsNonEmptyIsCheckedAsOne(string verb)
    {
        var rule = Rule(verb);
        foreach (var name in rule.Required.Where(name => NonEmpty.Contains(name, StringComparer.Ordinal)))
        {
            var args = Baseline(rule);
            args[name] = "   ";
            Assert.Contains(
                ArgumentProblems(rule, args),
                problem => problem.Contains($"argument '{name}' is empty", StringComparison.Ordinal));
        }
    }

    [Theory]
    [MemberData(nameof(Verbs))]
    public void EveryArgumentTheReferenceRestrictsToASetIsCheckedAgainstIt(string verb)
    {
        var rule = Rule(verb);
        foreach (var (name, values) in Enumerated.Where(pair => rule.Required.Contains(pair.Argument)))
        {
            var args = Baseline(rule);
            args[name] = "not_one_of_them";
            var problems = ArgumentProblems(rule, args);
            Assert.Contains(problems, problem => problem.Contains($"'{name}' is 'not_one_of_them'", StringComparison.Ordinal));
            Assert.All(values, value => Assert.DoesNotContain(
                ArgumentProblems(rule, Baseline(rule, value)),
                problem => problem.Contains($"'{name}' is '{value}'", StringComparison.Ordinal)));
        }
    }

    /// <summary>
    /// A rule arm written in a shape the reader has not seen is refused, not guessed at.
    ///
    /// This is the whole argument for generating the reference rather than writing it:
    /// a reader that quietly skipped an arm it did not understand would publish a
    /// document missing a verb, and nothing would say so.
    /// </summary>
    [Fact]
    public void AnArmWrittenInAnUnfamiliarShapeIsRefused()
    {
        var root = TreeWhere(
            ValidatorSource.RelativePath,
            source => source.Replace(
                "                required = [\"option_index\"];",
                "                required = SomeHelperNobodyHasWrittenYet();",
                StringComparison.Ordinal));

        var refusal = Assert.Throws<SourceRefusal>(() => ManifestFormatReference.Render(root));
        Assert.Contains("SomeHelperNobodyHasWrittenYet", refusal.Message, StringComparison.Ordinal);
        Directory.Delete(root, recursive: true);
    }

    /// <summary>
    /// An arm that decides one of its lists conditionally is refused too.
    ///
    /// A statement the reader cannot read is refused wherever it stands: the names still
    /// reach the page when only the assignments are looked at, so an arm that widens what
    /// it allows under a condition would publish the narrower set and call everything
    /// else refused.
    /// </summary>
    [Fact]
    public void AnArmThatReassignsAListUnderAConditionIsRefused()
    {
        var root = TreeWhere(
            ValidatorSource.RelativePath,
            source => source.Replace(
                "                nonNegativeIntegers = [\"option_index\"];",
                "                nonNegativeIntegers = [\"option_index\"];\n" +
                "                if (action.Seq > 0) allowed = [.. required, \"target_index\"];",
                StringComparison.Ordinal));

        var refusal = Assert.Throws<SourceRefusal>(() => ManifestFormatReference.Render(root));
        Assert.Contains(
            "does something other than assign its lists", refusal.Message, StringComparison.Ordinal);
        Directory.Delete(root, recursive: true);
    }

    /// <summary>
    /// A verb the validator accepts arguments for and no engine command executes is
    /// refused before anything is written, because a manifest using it would pass
    /// validation and then fail partway through a replay.
    /// </summary>
    [Fact]
    public void AVerbWithArgumentRulesAndNoEngineCommandIsRefused()
    {
        var row = File.ReadAllText(Path.Combine(Root, EngineCommandSource.RelativePath));
        var start = row.IndexOf("            Verb = ActionVerb.DiscardPotion,", StringComparison.Ordinal);
        var opening = row.LastIndexOf("        new()", start, StringComparison.Ordinal);
        var closing = row.IndexOf("        },", start, StringComparison.Ordinal) + "        },\n".Length;

        var root = TreeWhere(
            EngineCommandSource.RelativePath,
            source => source.Remove(opening, closing - opening));

        var refusal = Assert.Throws<SourceRefusal>(() => ManifestFormatReference.Render(root));
        Assert.Contains("DiscardPotion has argument rules and no engine command", refusal.Message, StringComparison.Ordinal);
        Directory.Delete(root, recursive: true);
    }

    /// <summary>
    /// Renaming the local a shop purchase binds its id argument to changes nothing.
    ///
    /// The name is bound from the source rather than spelled here, because a reader
    /// matching it by spelling would publish the local's name as a required argument
    /// after an ordinary rename and nothing would say so.
    /// </summary>
    [Fact]
    public void RenamingTheLocalTheShopBindsItsIdArgumentToChangesNothing()
    {
        var root = TreeWhere(
            ValidatorSource.RelativePath,
            source => source.Replace("idArgument", "boughtIdName", StringComparison.Ordinal));

        Assert.Equal(Spelled(ValidatorSource.ReadShopPurchaseKinds(Root)), Spelled(ValidatorSource.ReadShopPurchaseKinds(root)));
        Directory.Delete(root, recursive: true);
    }

    /// <summary>
    /// A shop rule whose required arguments no longer name that local is refused rather
    /// than published with the substitution silently not made.
    /// </summary>
    [Fact]
    public void AShopRuleThatNoLongerNamesItsIdArgumentIsRefused()
    {
        var root = TreeWhere(
            ValidatorSource.RelativePath,
            source => source.Replace(
                "idArgument is null ? Array.Empty<string>() : [idArgument, \"option_index\"]",
                "idArgument is null ? Array.Empty<string>() : [\"option_index\"]",
                StringComparison.Ordinal));

        var refusal = Assert.Throws<SourceRefusal>(() => ManifestFormatReference.Render(root));
        Assert.Contains("does not name 'idArgument' exactly once", refusal.Message, StringComparison.Ordinal);
        Directory.Delete(root, recursive: true);
    }

    /// <summary>
    /// A verb with two engine-command rows is refused by name, because the reference
    /// would otherwise print one of them and fail with a stack trace on the way there.
    /// </summary>
    [Fact]
    public void AVerbWithTwoEngineCommandRowsIsRefused()
    {
        var table = File.ReadAllText(Path.Combine(Root, EngineCommandSource.RelativePath));
        var start = table.IndexOf("            Verb = ActionVerb.DiscardPotion,", StringComparison.Ordinal);
        var opening = table.LastIndexOf("        new()", start, StringComparison.Ordinal);
        var closing = table.IndexOf("        },", start, StringComparison.Ordinal) + "        },\n".Length;
        var row = table[opening..closing];

        var root = TreeWhere(
            EngineCommandSource.RelativePath,
            source => source.Insert(closing, row));

        var refusal = Assert.Throws<SourceRefusal>(() => ManifestFormatReference.Render(root));
        Assert.Contains("DiscardPotion has 2 rows in the engine-command table", refusal.Message, StringComparison.Ordinal);
        Directory.Delete(root, recursive: true);
    }

    private static IReadOnlyList<string> Spelled(
        IReadOnlyList<(string Kind, IReadOnlyList<string> Required)> kinds) =>
        kinds.Select(kind => $"{kind.Kind}: {string.Join(", ", kind.Required)}").ToList();

    /// <summary>A copy of the two declarations the reference is generated from, with one changed.</summary>
    private static string TreeWhere(string relativePath, Func<string, string> change)
    {
        var root = Path.Combine(Path.GetTempPath(), Path.GetRandomFileName());
        foreach (var path in new[] { ValidatorSource.RelativePath, EngineCommandSource.RelativePath })
        {
            var destination = Path.Combine(root, path);
            Directory.CreateDirectory(Path.GetDirectoryName(destination)!);
            var source = File.ReadAllText(Path.Combine(Root, path));
            File.WriteAllText(destination, path == relativePath ? change(source) : source);
        }

        return root;
    }

    private static VerbArguments Rule(string verb) => Rules.Single(rule => rule.Verb == verb);

    /// <summary>Exactly the required arguments, each carrying a value its own rules accept.</summary>
    private static SortedDictionary<string, string> Baseline(VerbArguments rule, string? enumeratedChoice = null)
    {
        var args = new SortedDictionary<string, string>(StringComparer.Ordinal);
        foreach (var name in rule.Required)
        {
            args[name] = Acceptable(name, rule, enumeratedChoice);
        }

        return args;
    }

    /// <summary>
    /// A value this argument accepts.
    ///
    /// The one place with a choice to make is a shop purchase's kind, because four of
    /// the five oblige the action to carry more than the reference calls required. The
    /// kind that obliges nothing is the one a baseline can use, and which kind that is
    /// is asked of the same reader rather than written down here.
    /// </summary>
    private static string Acceptable(string name, VerbArguments rule, string? enumeratedChoice)
    {
        if (rule.NonNegativeIntegers.Contains(name, StringComparer.Ordinal)) return "1";

        if (Enumerated.FirstOrDefault(pair => pair.Argument == name) is { Values: not null } restricted)
        {
            return enumeratedChoice is not null && restricted.Values.Contains(enumeratedChoice, StringComparer.Ordinal)
                ? enumeratedChoice
                : Unencumbered(restricted.Values);
        }

        return "an_id";
    }

    private static string Unencumbered(IReadOnlyList<string> values)
    {
        var kinds = ValidatorSource.ReadShopPurchaseKinds(Root)
            .Where(kind => values.Contains(kind.Kind, StringComparer.Ordinal))
            .ToList();

        return kinds.Count == 0 ? values[0] : kinds.MinBy(kind => kind.Required.Count).Kind;
    }

    /// <summary>A value that is valid and is not the one the baseline already took.</summary>
    private static string Distinct(string name, VerbArguments rule) =>
        rule.NonNegativeIntegers.Contains(name, StringComparer.Ordinal) ? "99" : "another_id";

    /// <summary>
    /// What the validator says about this action's arguments, and nothing else.
    ///
    /// The action is appended to a manifest the validator already accepts, so a
    /// complaint here is about the arguments under test rather than about a fixture
    /// broken in three ways. Problems naming any other action, or naming this one for a
    /// reason other than an argument, are somebody else's test.
    /// </summary>
    private static IReadOnlyList<string> ArgumentProblems(
        VerbArguments rule, IReadOnlyDictionary<string, string> args)
    {
        var manifest = Fixtures.ValidManifest();
        var last = manifest.Actions[^1];
        var at = last.Seq + 1;
        var when = Math.Max(
            last.Evidence!.VideoTimeMs!.Value,
            manifest.Checkpoints.SelectMany(checkpoint => checkpoint.Expect.Values)
                .Max(fact => fact.Evidence?.VideoTimeMs ?? 0)) + 1000;

        var probed = manifest with
        {
            Actions =
            [
                .. manifest.Actions,
                new ActionRecord
                {
                    Seq = at,
                    Verb = Enum.Parse<ActionVerb>(rule.Verb),
                    Args = args,
                    Source = FactSource.Observed,
                    Evidence = FactEvidence.AtVideoTime(when, "format reference probe"),
                },
            ],
        };

        return ManifestValidator.Validate(probed).Problems
            .Where(problem => problem.Contains($"actions[{at}] ", StringComparison.Ordinal))
            .Where(problem => problem.Contains("argument", StringComparison.Ordinal))
            .ToList();
    }
}
